version: '3.3'
services:
  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    expose:
      - ${DB_PORT}
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
